
get http://127.0.0.1:5000/highscores?sort=none&pw=monkeyisland

###

post http://127.0.0.1:5000/api/highscores?pw=monkeyisland
content-type: application/json

{"player_name": "Johnny", "overall_highscore": 50}

###

get http://127.0.0.1:5000/api/highscores?pw=monkeyisland

###

get http://127.0.0.1:5000/api/highscores?limit=5&pw=monkeyisland

###

get http://127.0.0.1:5000/api/highscores?sort=asc&limit=2&pw=monkeyisland

###

get http://127.0.0.1:5000/api/scores?sort=desc&limit=10&pw=secret

###

delete http://127.0.0.1:5000/api/highscores/4?pw=monkeyisland

###

get http://127.0.0.1:5000/api/highscores/4?pw=monkeyisland

###