
get http://127.0.0.1:5000/highscores

###

post http://127.0.0.1:5000/highscores
content-type: application/json

{"id": 1, "name": "dummy", "level": 1, "score": 100}

###

get http://127.0.0.1:5000/api/scores/1?pw=secret

###

get http://127.0.0.1:5000/api/scores?limit=10&pw=secret

###

get http://127.0.0.1:5000/api/scores?sort=asc&pw=secret

###

get http://127.0.0.1:5000/api/scores?sort=desc&pw=secret

###

get http://127.0.0.1:5000/api/scores?sort=desc&limit=10&pw=secret

###

delete http://127.0.0.1:5000/api/highscores/1

###

get http://127.0.0.1:5000/api/highscores/1

###

post http://127.0.0.1:5000/api/new_player
content-type: application/json

{"name": "james", "email": "james@gmail.com"}

###